singleQuote: true
tabWidth: 4
userTabs: true
bracketSpacing: true
bracketSameLine: false
semi: true
printWidth: 120
singleAttributePerLine: false
wrapAttributes: 'auto'
overrides:
    - files: '*.html'
      options:
          parser: angular
